### ISSUE TITLE
gpu support 

### ISSUE THREAD

**Issue by fighting-liu** [tobegit3hub/simple_tensorflow_serving#12]
From your introduction, it says "support inference with accelerated GPU". How to make it happen? Thanks!

**Comment by tobegit3hub** [comment]
Sorry for the late reply.

It does support GPU inference because we use TensorFlow Python APIs which supports GPU. You can install `tensorflow-gpu` and configure CUDA dependencies before running `simple_tensorflow_serving`.

**Comment by PurvangL** [comment]
can it support GPU vendor other than Nvidia such as AMD?
