### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rhyspang** [tobegit3hub/simple_tensorflow_serving#13]
hi,
 First of all, thanks for working on this repository. appreaciated! 👍 
 
When I use 'simple_tensorflow_serving model_base_path="./models/tensorflow_template_application_model"', I got an error :
from gen_client import gen_client
ModuleNotFoundError: No module named 'gen_client'

I cannot tell why this error happened, looking forward to your reply!

**Comment by tobegit3hub** [comment]
This has been fixed by https://github.com/tobegit3hub/simple_tensorflow_serving/pull/20 .
