### ISSUE TITLE
请问用image做inference的时候这个报错是什么意思？

### ISSUE THREAD

**Issue by CyLouisKoo** [tobegit3hub/simple_tensorflow_serving#21]
![image](https://user-images.githubusercontent.com/22675525/43382934-ffc9a5de-940b-11e8-8fe1-d17f34b63aff.png)

**Comment by tobegit3hub** [comment]
It seems that you are requesting with the "input" data but it is not in the model signature.

For image inference, we recommend you to export the image model with "images" as inputs and the clients should request with the "images" data instead of "input".

**Comment by CyLouisKoo** [comment]
How to do it specifically? Suppose I have the following ready-made model. How can I quickly call this model, is there a ready-made solution? Appreciate much~
![image](https://user-images.githubusercontent.com/22675525/43395901-5828d972-9432-11e8-8f4f-fa75a2312a46.png)

**Comment by tobegit3hub** [comment]
Thanks for your response. I have updated the [deep_image_model](https://github.com/tobegit3hub/simple_tensorflow_serving/tree/master/models/deep_image_model/) with image base64 as input.

Now you can `git pull` to get the latest pre-trained model and test with this commands.

```
simple_tensorflow_serving --model_base_path="./models/deep_image_platforms"

curl -X POST -F 'image=@./images/mew.jpg' -F "model_version=1" 127.0.0.1:8500
```

**Comment by tobegit3hub** [comment]
Great and thanks for reporting the issue.

I'm gonna close the issue and feel free to re-open if you have any other question.
