### ISSUE TITLE
"error":"Invalid json data:

### ISSUE THREAD

**Issue by Johnson-yue** [tobegit3hub/simple_tensorflow_serving#25]
Thank your reply! I check your update and still questions:

1. I run `simple_tensorflow_serving --model_base_path="./models/tensorflow_template_application_model"` and then run `curl http://localhost:8500/v1/models/__tensorflow_template_application_model__/gen_client?language=python > client.py`  but the shell output:
#### zsh: no matches found: http://localhost:8500/v1/models/tensorflow_template_application_model/gen_client?language=python

2. I replace `tensorflow_template_application_model` with `default` in model_config_file.json like this:
![image](https://user-images.githubusercontent.com/10268274/45136689-e69e0200-b1d7-11e8-9fed-b644eee30a82.png) 
and the I run `simple_tensorflow_serving --model_config_file="./examples/model_config_file.json"`
__simple_tensorflow_serving__ is runing:
![image](https://user-images.githubusercontent.com/10268274/45136753-2b299d80-b1d8-11e8-9d3d-40dd284f8fc9.png)

In other terminal, I run `python client.py`:
![image](https://user-images.githubusercontent.com/10268274/45136835-865b9000-b1d8-11e8-8bfc-72903ace0ffd.png)
the output is like this : 
![image](https://user-images.githubusercontent.com/10268274/45136846-9d9a7d80-b1d8-11e8-9409-28ca46f76bc2.png)

So. I have test your web __Test_ function:
![image](https://user-images.githubusercontent.com/10268274/45136877-c589e100-b1d8-11e8-90da-c33eba8b53a5.png)
result is the same. I can not get right result..

My input_data of client.py is wrong??

**Comment by Johnson-yue** [comment]
your docker image is everything OK.

**Comment by tobegit3hub** [comment]
It seems to be the problem of input json. Make sure you use the "gen_client" and the clients in this repo.

Did you run your server with Python3?

**Comment by Johnson-yue** [comment]
@tobegit3hub  yes，my python version is 3.5

**Comment by tobegit3hub** [comment]
Another issue for Python 3 in https://stackoverflow.com/questions/18686903/dict-keys0-on-python-3 .

And we use `has_key` in `tensorflow_inference_service.py`.
