### ISSUE TITLE
How to limited GPU memory?

### ISSUE THREAD

**Issue by Johnson-yue** [tobegit3hub/simple_tensorflow_serving#27]
Hi, I update your docker image `tobegit3hub/simple_tensorflow_serving:latest-gpu`  and test it.
I found some problems:
   1.  your docker default run `simple_tensorflow_serving --model_config_file="./examples/model_config_file.json"` but  do not install __ONNX__, it is a small problem!

   2.  tf-serving -gpu  default is allocation __ALL GPU Memory__ it was so terrible!!! [look here](https://github.com/tensorflow/serving/issues/249)  , and luckly some have fixed it [fixed code](https://github.com/tensorflow/serving/issues/249#issuecomment-293989870), 
  Can you add  these config and re-compile the TF-Serving. 
   By the way , the method is _per_process_gpu_memory_fraction_ but I think  `allow_growth=True` but I do not know how to do it.
I think the usage of gpu depend on model mybe right?

**Comment by tobegit3hub** [comment]
For the first question, we don't need the `onnx` python package because we use `onnx_python` which is already merged in `mxnet` python package. I think you can run all the ONNX without any other problem.

We can add the parameters such as `per_process_gpu_memory_fraction` to control the GPU devices soon.

**Comment by Johnson-yue** [comment]
@tobegit3hub  Oh, Mybe I have something wrong, I will check it. I will look forward to new version with parameters of Controling the GPU device

**Comment by tobegit3hub** [comment]
It is supported now and you can use it with `pip install -U simple_tensorflow_serving>=0.6.4`.

More usage refers to https://github.com/tobegit3hub/simple_tensorflow_serving#gpu-acceleration .
