### ISSUE TITLE
Model does not work , output is alway the same! not change

### ISSUE THREAD

**Issue by Johnson-yue** [tobegit3hub/simple_tensorflow_serving#29]
Hi, I update your docker image and test my model which saved by SavedModel function. my model just is resnet_50 for classification, when __I saved model as SavedModel format, the result did not change whether I changed any input picture__ ???

My Model have problem? what is wrong with my model or some reason?

 Here is my saved model code : 
![image](https://user-images.githubusercontent.com/10268274/45412464-40576e00-b6a9-11e8-8d2c-3f9b1156f501.png)

![image](https://user-images.githubusercontent.com/10268274/45412484-4ea58a00-b6a9-11e8-9b25-0e583d027f39.png)

First, I build a resnet_50 compute graph ,
and then I  reload graph and restore weights from checkpoint.
Finally, I use tf.saved_model to save  and everything is ok. I have no error or trouble.

I write client code for it , here:
![image](https://user-images.githubusercontent.com/10268274/45412646-c5db1e00-b6a9-11e8-996b-00e62c95d279.png)
In client code , first I read a image into numpy.array, 
 then convert data of image to [1, 64, 64 ,3] dtype=float32, and  convert numpy to list .  
Finally, send a requests like code and show all result.

the result is always is:
![image](https://user-images.githubusercontent.com/10268274/45412856-587bbd00-b6aa-11e8-8944-49714479ee07.png)

![image](https://user-images.githubusercontent.com/10268274/45413045-c6c07f80-b6aa-11e8-80d8-8ee0ace84786.png)

**Comment by Johnson-yue** [comment]
@tobegit3hub  thanks for your reply, it is my mistakes. I check the input data. it is the same. I think the reason is opencv2 and opencv3 difference!.  When I use opencv3 python api,  the result is correct! Thank you

**Comment by tobegit3hub** [comment]
You are welcome. Thanks for your report 👍
