### ISSUE TITLE
可以用于搭建tensorflow_serving模型服务平台吗？

### ISSUE THREAD

**Issue by LongQi** [tobegit3hub/simple_tensorflow_serving#3]
请教个问题，现在我们有需求搭建机器学习的模型服务平台，看到simple_tensorflow_serving，感觉这个工具还是很方便的，对于启动一个tensorflow serving和客户端的请求来说都很方便很灵活。
可是机器学习的模型服务平台又会涉及到模型的更新、自动化的部署、弹性扩容、灰度发布、测试和验证等多方面的内容，您觉得要做到这些，结合simple_tensorflow_serving，可以从哪些方面来考虑，会不会用到docker。
多谢！

**Comment by tobegit3hub** [comment]
Thanks for your attention.

Simple TensorFlow Serving focus on loading and serving machine learning models which supports TensorFlow SavedModel and MXNet checkpoint now. It can load multiple models at the same time and re-load the TensorFlow models automatically. If you want to put model versions online/offline, you can simply add/remove the model files, just like TensorFlow Serving.

However, if you want to deploy the serving service in cluster and support rolling update, you need the service management cluster and I would recommend Kubernetes or the similar orchestration tools.

Now Simple TensorFlow Serving has provided the docker image and you can pull from the public registry with `docker pull tobegit3hub/simple_tensorflow_serving`. You can use this docker image to deploy the model services for machine learning very easily.

**Comment by LongQi** [comment]
Thank you very much.

**Comment by tobegit3hub** [comment]
I will close this because it is not the issue of this project.

Feel free to re-open this if you have any other questions.
