### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by crius79** [tobegit3hub/simple_tensorflow_serving#4]
run in　open statck centos：

python server.py 
Illegal instruction (core dumped)

**Comment by tobegit3hub** [comment]
What is the version of Python are you using? @crius79

**Comment by tobegit3hub** [comment]
I'm pretty sure it is related to your environment. Can you try this with docker image or your local environment?

**Comment by crius79** [comment]
python 2.7.5.

The same version in my VirtualBox virtual machine, in which it works well.

Maybe it relates some CPU issue unknown, because it uses the bin file which not compiles for the dedicated machine environment.

I will not focus on this issue, since successfully compiled the Tensorflow Serving  and connected well with my Golang client code.

Anyway, thanks a lot for your great work .

It provides useful log information, compared with logs in our output code helped me debug the Golang client input code.

**Comment by tobegit3hub** [comment]
Thanks for your usage if it helps. It is great to provide more useful information and feel free to make contribution for this project 😃
