### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by yzxchn** [tobegit3hub/simple_tensorflow_serving#40]
In a clean Python 2.7 `virtualenv`, with the command `pip install simple_tensorflow_serving`, then `simple_tensorflow_serving -h`, I get the error `ImportError: No module named PIL`.

It appears that the package `pillow` is not installed together with `simple_tensorflow_serving` as a dependency.

**Comment by tobegit3hub** [comment]
Nice catch and thanks for reporting.
