### ISSUE TITLE
Unable to run local trained model

### ISSUE THREAD

**Issue by MaybeShewill-CV** [tobegit3hub/simple_tensorflow_serving#43]
I have convert one of my pretrained network weights into tensorflow saved model and use the check tools you supplied which shows nothing wrong. But when I run the image inference from the broswer I
got following mistake. Could you please help me to locate which step may be wrong. Thanks a lot. Here is some information
![question](https://user-images.githubusercontent.com/15725187/54361304-b7de7800-46a1-11e9-9ec6-161e9b6dc86b.png)
![ques](https://user-images.githubusercontent.com/15725187/54361411-e6f4e980-46a1-11e9-873a-5545c6b04319.png)

**Comment by tobegit3hub** [comment]
Thanks for reporting.

This page is for image model which requires specified model signature. Could you try with the `codegen` python client to test with your model?

**Comment by MaybeShewill-CV** [comment]
@tobegit3hub Sorry I have solved the problem. I forget to close this issue. By the way can I ask for another help that may has little relationship with this project. The problem is that when I run a server within a tensorflow serving docker container and run a grpc client outside of the container everything works fine without vpn connection but it will not work when I establish the vpn connection. During the two process the server address are both localhost:9000. Could you please help me with it if you've got spare time:)

**Comment by tobegit3hub** [comment]
This seems to be the issue of your VPN. I don't know how you setup it and use it, so I have no methods to address this. But you can try run docker container with `--net=host` so that it uses the host network and make sure the client can access the server.

**Comment by MaybeShewill-CV** [comment]
@tobegit3hub Thanks a lot:)
