### ISSUE TITLE
If I want to deploy module on cross-platform

### ISSUE THREAD

**Issue by yingwei13mei** [tobegit3hub/simple_tensorflow_serving#44]
If I want to deploy module on different-platform. For example I trained the module in python -Tensorflow enviroment. But I expect to use this module file in C++ windows env. 
I reference some views on TF Serving saved_model_builder() function, it seems like a workable solution. And how could it easily transfer module in different platform within current solution? 

Just some thinking about current project.

**Comment by tobegit3hub** [comment]
I'm not sure if I completely understand what you mean. No mather what languages(Python or C++) you use for TensorFlow, the model file is an protobuf file and we need to use `saved_model_builder()` to set the model signature. Then you can use this model file in Python, C++ or any other languages which can read TensorFlow SavedModel file.
