### ISSUE TITLE
A little bit more documentation, what are keys?

### ISSUE THREAD

**Issue by hellsan631** [tobegit3hub/simple_tensorflow_serving#56]
Sorry for the noob question, but I'm new to the world of neural networks.

I have been doing some digging, but am unable to find out what the significance of keys within the input data.

```
input_data = {
  ...
  "data": {
      "keys": [[11.0], [2.0]],
      "features": [[1, 1, 1, 1, 1, 1, 1, 1, 1],
                   [1, 1, 1, 1, 1, 1, 1, 1, 1]]
  }
}
```

As far as I'm aware, features are the input for the neural network, in the above case, a 2d tensor. 

What is the significance of ```keys``` and how do they correlate to the input to the neural network?

**Comment by tobegit3hub** [comment]
The keys in this example is related to your model signature. That means you can change the keys of requests for your own TensorFlow models and this json only works for the example TensorFlow models in this project.
