### ISSUE TITLE
How to run in docker?

### ISSUE THREAD

**Issue by jimmy-walker** [tobegit3hub/simple_tensorflow_serving#64]
I use the docker way of installation.
But when I run the command `docker run -d -p 8500:8500 tobegit3hub/simple_tensorflow_serving`, I donnot know how to pass the set `simple_tensorflow_serving --model_base_path="./models/tensorflow_template_application_model"` to container.
Appreciate for any help.

**Comment by wyqnumber** [comment]
+1

**Comment by wzl789139** [comment]
$docker exec -it containerID bash
#use this command ,you can enter the container,then input the command to run

**Comment by tobegit3hub** [comment]
You can use more docker parameters like `-v` to mount model files into the docker container.

For testing, I always run with `docker run -it -p 8500:8500 -v /:/host tobegit3hub/simple_tensorflow_serving bash` so that I can run the server by myself and read any model files in the host server.
