### ISSUE TITLE
i run it with server.py,but it cant import the package in same dir.how can i fix it?

### ISSUE THREAD

**Issue by rithd** [tobegit3hub/simple_tensorflow_serving#65]

**Comment by rithd** [comment]
File "server.py", line 18, in <module>
    from .tensorflow_inference_service import TensorFlowInferenceService
ValueError: Attempted relative import in non-package

i find _init_.py , but it still cant import it.

**Comment by tobegit3hub** [comment]
This has been fixed for Python 2 and Python 3. Please upgrade with `pip install -U simple_tensorflow_serving>=0.8.2".

Now we recommend to use the command `simple_tensorflow_serving` or `stfs` which is much easier.
