### ISSUE TITLE
ImportError: No module named simple_tensorflow_serving.server 

### ISSUE THREAD

**Issue by jeffin07** [tobegit3hub/simple_tensorflow_serving#67]
First I like to thank you for making this project because it's more user friendly than the tensorflow serving i have played around with tensorflow serving simple tensorflow serving and i really like simple tensorflow serving it really justifies it's name. 

To the problem i trained a small model using the tensorflow flowers example from their official page but when i run the saved model file with simple tensorflow servings i get this error

`ImportError: No module named simple_tensorflow_serving.server
unable to load app 0 (mountpoint='') (callable not found or import error)`

When i press ctrl+c it shows 

`- worker 1 (pid: 13294) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
goodbye to uWSGI.
`

Anybody ever encountered this before ?

**Comment by tobegit3hub** [comment]
It is fixed by using flask server instead of uwsgi by default.

Please try with the latest code or using 0.8.1.1 or above versions.
