### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by mke21** [tobegit3hub/simple_tensorflow_serving#7]
Python 2.7 will reach end-of-life in 2020. Is it possible to port this code to Python3? I tested and it did not work under python 3.4.

**Comment by tobegit3hub** [comment]
Off course we should do it. I will test in containers with `Python 3+` soon.

**Comment by tobegit3hub** [comment]
I have test in `Python 3.4` and it seems we have something to fix.

Firstly, the `cStringIO` has been changed to `io.StringIO`. Secondly, the import path need to be changed for `Python 3`. I will checkout how to modify these to be compatible with both `Python 2` and `Python 3`.

**Comment by tobegit3hub** [comment]
Thanks @mke21 and it supports Python 3 now.

We have test in `Python 3.4` docker image with `simple_tensorflow_serving 0.4.1`.
