### ISSUE TITLE
docker python  3.7

### ISSUE THREAD

**Issue by sonfire86** [tobegit3hub/simple_tensorflow_serving#72]
Do you plan to upgrade docker to python 3.7?

**Comment by tobegit3hub** [comment]
Of course we can.

Feel free to contribute the pull-request about this. And we may add the `Dockerfile.latest-py37` to support Python 3.7 in the future.

**Comment by tobegit3hub** [comment]
Dockerfile for Python 3.7 has been merged by https://github.com/tobegit3hub/simple_tensorflow_serving/commit/6aa1aad5f2cb68d195beddb5af2f249adbffa6bd .
