### ISSUE TITLE
block when enable_ssl is False

### ISSUE THREAD

**Issue by wykdg** [tobegit3hub/simple_tensorflow_serving#80]
in server.py

def main():
  app = WsgiApp(args).app

  # Run with Flask HTTP server
  if args.enable_ssl:
    # Can pass ssl_context="adhoc" for auto-sign certification
    app.run(
        host=args.host,
        port=args.port,
        threaded=True,
        debug=args.debug,
        ssl_context=(args.secret_pem, args.secret_key))
  else:
    # TODO: Use single thread by default
    app.run(host=args.host, port=args.port, threaded=False, debug=args.debug)

when use python_predict_client on the website,it will block

**Comment by tobegit3hub** [comment]
The default configuration of `enable_ssl` is disable(false)  and I'm sure it's not the issue of SSL.

Please try to request the server in web browser or command line(curl). It would be better if we get the log of the server and the client response.
