### ISSUE TITLE
 What is the difference between it and tensorflow serving? What are the advantages? Where can I see its  benchmarks about inference performance test？?

### ISSUE THREAD

**Issue by charmby** [tobegit3hub/simple_tensorflow_serving#82]
What is the difference between it and tensorflow serving? What are the advantages? Where can I see its  benchmarks about inference performance test？?

**Comment by tobegit3hub** [comment]
The result of benchmark in the README https://github.com/tobegit3hub/simple_tensorflow_serving#performance . And you can test by yourself with the scripts in [./benchmark](https://github.com/tobegit3hub/simple_tensorflow_serving/tree/master/benchmark).

You can see all the features in README which are quite different from `tensorflow/serving`.

**Comment by charmby** [comment]
> The result of benchmark in the README https://github.com/tobegit3hub/simple_tensorflow_serving#performance . And you can test by yourself with the scripts in [./benchmark](https://github.com/tobegit3hub/simple_tensorflow_serving/tree/master/benchmark).
> 
> You can see all the features in README which are quite different from `tensorflow/serving`.

Thanks so much for your reply.
