### ISSUE TITLE
if I will deploy a tf 1.x version SavedModel  how to do ？

### ISSUE THREAD

**Issue by Johnson-yue** [tobegit3hub/simple_tensorflow_serving#85]
I  use your docker image : latest-gpu   but it default install tensorflow 2.x  
and my SavedModel is tf 1.x version so How I deploy it ？？

**Comment by tobegit3hub** [comment]
It's okay to deploy TF 1.x models and 2.x models because they are compatible. The only think you have to resolve is the difference of operators support. 

If you want to use the TF 1.x operators, you can uninstall the TF in docker and install the new TensorFlow in your expected version.
