### ISSUE TITLE
docker run with models_config.json

### ISSUE THREAD

**Issue by zhoujiang2013** [tobegit3hub/simple_tensorflow_serving#88]
how can i use simple_tensorflow_serving like tensorflow serving, docker run with models_config.json

docker run -d -p 8500:8500 -v /root/save_path:/root/save_path tobegit3hub/simple_tensorflow_serving --model_config_file="/root/save_path/models_config.json"

i got the error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--model_config_file=/root/save_path/models_config.json\": stat --model_config_file=/root/save_path/models_config.json: no such file or directory": unknown.

**Comment by tobegit3hub** [comment]
@zhoujiang2013 You can mount the config file in the docker container with `docker run -v`.
